drop table role if exists;

create table role
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name VARCHAR(32) DEFAULT 'DEFAULT'
);

insert into role(id, name)
values (1, '管理员'),
       (2, '游客');